package com.incidentplatform.application.agent.model;

import com.incidentplatform.domain.enums.Severity;
import lombok.Builder;

import java.util.List;
import java.util.UUID;

/**
 * AgentInput — Input payload containing all intermediate findings passed between agents in the pipeline.
 */
@Builder
public record AgentInput(
    UUID incidentId,
    String title,
    String description,
    Severity severity,
    String serviceName,
    String environment,
    String logsContext,           // Logs gathered for analysis
    List<String> runbooksContext,  // Runbooks gathered by the Knowledge Base Agent
    String plannerOutput,         // Step-by-step checklist generated by the Planner Agent
    String logMetricsOutput       // Log analysis findings generated by LogMetrics Agent
) {}
