package com.incidentplatform.application.agent.model;

import java.math.BigDecimal;

/**
 * AgentResult — Immutable record representing the output generated by an AI Agent.
 */
public record AgentResult(
    String findings,
    String reasoning,
    BigDecimal confidenceScore
) {}
